### ISSUE TITLE
Offering help for developing this library

### ISSUE THREAD

**Issue by kristerkari** [daniloster/react-native-sass-classname#10]
Hi @daniloster,

I really like the idea behind this library. I know that React native stylesheets != CSS, but that does not mean that there couldn't be some shared styles between web and native.

I did a bit of testing of the library on my project and found some "rough edges" that could possibly be improved (issues #7, #8, #9).

I'd like to help out with fixing and implementing things, but I need a bit of help with getting to know the code and bouncing some ideas around.

**Comment by daniloster** [comment]
Sorry taking long. I would love any contribution.

**Comment by daniloster** [comment]
Feel free to put some PRs. I have been busy these days and I will try to check the repo as much as possible. @daniloster is my twitter handle (PM me there).

**Comment by kristerkari** [comment]
Hi @daniloster no worries, and thanks for replying.

I had a look at the code from this repo and quickly realised that in order to develop the features that I needed, there needs to be a proper way to do unit testing and  the code needs to be split into multiple plugins that only do one thing.

That's why I went ahead and created these libraries based on what you had created:
* [react-native-css-transformer](https://github.com/kristerkari/react-native-css-transformer) 
* [react-native-sass-transformer](https://github.com/kristerkari/react-native-sass-transformer)
* [babel-plugin-react-native-platform-specific-extensions](https://github.com/kristerkari/babel-plugin-react-native-platform-specific-extensions)
* [babel-plugin-react-native-classname-to-style](https://github.com/kristerkari/babel-plugin-react-native-classname-to-style)

If you want to implement any of the requested features for this plugin, you can most likely import them from any of my libraries.

Thanks!

**Comment by daniloster** [comment]
That is great! I know that my absence here has not helped you enough.
I will try to contribute. Also, I will redirect my repo to point to babel-plugin-react-native-classname-to-style, which seems to be the end plugin.

Congrats!

**Comment by daniloster** [comment]
@kristerkari ^^

**Comment by kristerkari** [comment]
@daniloster Cool :) actually it's not just that babel plugin that you mentioned, I created multiple plugins, here are the docs describing how everything works:
https://github.com/kristerkari/react-native-css-modules
